<?php
/**
 * Bank Pertanyaan Generik (Many-to-Many)
 * ============================================================
 * Berbeda dari desain awal (1 pertanyaan hanya untuk 1 jurusan), setiap
 * pertanyaan di sini dapat mendukung BEBERAPA jurusan sekaligus dengan
 * nilai belief yang berbeda-beda -- sesuai konsep asli Dempster-Shafer
 * dan sesuai spesifikasi awal proyek ("Satu pertanyaan dapat mendukung
 * beberapa jurusan").
 *
 * Total: 150 pertanyaan, dibagi 3 layer @ 50 pertanyaan (untuk keperluan
 * pengelompokan tampilan), mencakup 5 kategori evidence:
 * minat, bakat, kemampuan, kepribadian, tujuan_karier.
 *
 * Format tiap item:
 *   ['teks' => '...', 'kategori' => '...', 'rules' => ['Nama Jurusan' => belief, ...]]
 */

return [

    // ================= LAYER 1 (Q1-50): KESEHATAN, SAINS, TEKNOLOGI =================
    ['teks' => 'Saya menyukai pelajaran Biologi', 'kategori' => 'minat', 'rules' => ['Kedokteran' => 0.75, 'Kedokteran Gigi' => 0.70, 'Keperawatan' => 0.68, 'Biologi' => 0.80, 'Gizi' => 0.65, 'Kedokteran Hewan' => 0.70, 'Agroteknologi' => 0.55]],
    ['teks' => 'Saya ingin membantu menyembuhkan orang sakit', 'kategori' => 'tujuan_karier', 'rules' => ['Kedokteran' => 0.90, 'Kedokteran Gigi' => 0.75, 'Keperawatan' => 0.85, 'Farmasi' => 0.55, 'Kedokteran Hewan' => 0.45]],
    ['teks' => 'Saya tidak takut melihat darah atau luka', 'kategori' => 'kepribadian', 'rules' => ['Kedokteran' => 0.80, 'Kedokteran Gigi' => 0.65, 'Keperawatan' => 0.78, 'Kedokteran Hewan' => 0.70]],
    ['teks' => 'Saya mampu bekerja dengan teliti dan sabar dalam waktu lama', 'kategori' => 'kemampuan', 'rules' => ['Kedokteran' => 0.72, 'Kedokteran Gigi' => 0.80, 'Farmasi' => 0.70, 'Keperawatan' => 0.65, 'Akuntansi' => 0.55]],
    ['teks' => 'Saya tertarik pada obat-obatan dan cara kerja senyawa kimia dalam tubuh', 'kategori' => 'minat', 'rules' => ['Farmasi' => 0.88, 'Kedokteran' => 0.45, 'Kimia' => 0.55]],
    ['teks' => 'Saya senang merawat dan mendampingi orang lain yang sedang sakit', 'kategori' => 'minat', 'rules' => ['Keperawatan' => 0.88, 'Kedokteran' => 0.50, 'Bimbingan dan Konseling' => 0.40, 'Psikologi' => 0.40]],
    ['teks' => 'Saya tertarik pada pola makan sehat dan kandungan gizi makanan', 'kategori' => 'minat', 'rules' => ['Gizi' => 0.88, 'Ilmu dan Teknologi Pangan' => 0.55, 'Kedokteran' => 0.35]],
    ['teks' => 'Saya menyukai dan peduli pada kesehatan serta perawatan hewan', 'kategori' => 'minat', 'rules' => ['Kedokteran Hewan' => 0.90, 'Peternakan' => 0.50, 'Biologi' => 0.40]],
    ['teks' => 'Saya menyukai komputer dan senang mengulik teknologi baru', 'kategori' => 'minat', 'rules' => ['Teknik Informatika' => 0.85, 'Ilmu Komputer' => 0.85, 'Sistem Informasi' => 0.65, 'Teknik Komputer' => 0.75, 'Data Science' => 0.60, 'Keamanan Siber' => 0.65]],
    ['teks' => 'Saya tertarik membuat aplikasi, website, atau program komputer', 'kategori' => 'minat', 'rules' => ['Teknik Informatika' => 0.90, 'Ilmu Komputer' => 0.80, 'Sistem Informasi' => 0.60, 'Bisnis Digital' => 0.40]],
    ['teks' => 'Saya senang memecahkan teka-teki logika dan algoritma', 'kategori' => 'bakat', 'rules' => ['Teknik Informatika' => 0.80, 'Ilmu Komputer' => 0.85, 'Matematika' => 0.60, 'Data Science' => 0.70, 'Statistika' => 0.55]],
    ['teks' => 'Saya menyukai pelajaran Matematika', 'kategori' => 'minat', 'rules' => ['Matematika' => 0.88, 'Statistika' => 0.80, 'Aktuaria' => 0.82, 'Teknik Informatika' => 0.55, 'Ilmu Komputer' => 0.55, 'Fisika' => 0.60, 'Akuntansi' => 0.50, 'Ekonomi Pembangunan' => 0.50, 'Teknik Elektro' => 0.50]],
    ['teks' => 'Saya tertarik pada isu keamanan data dan celah sistem komputer', 'kategori' => 'minat', 'rules' => ['Keamanan Siber' => 0.90, 'Teknik Informatika' => 0.45, 'Teknik Komputer' => 0.50]],
    ['teks' => 'Saya senang mengolah dan menganalisis data dalam jumlah besar', 'kategori' => 'kemampuan', 'rules' => ['Data Science' => 0.88, 'Statistika' => 0.85, 'Sistem Informasi' => 0.55, 'Aktuaria' => 0.60, 'Ekonomi Pembangunan' => 0.45]],
    ['teks' => 'Saya menyukai pelajaran Fisika', 'kategori' => 'minat', 'rules' => ['Fisika' => 0.88, 'Teknik Elektro' => 0.75, 'Teknik Mesin' => 0.72, 'Teknik Sipil' => 0.60, 'Teknik Perkapalan' => 0.70, 'Geografi' => 0.40]],
    ['teks' => 'Saya tertarik pada kelistrikan, rangkaian, dan elektronika', 'kategori' => 'minat', 'rules' => ['Teknik Elektro' => 0.88, 'Teknik Komputer' => 0.55, 'Fisika' => 0.45]],
    ['teks' => 'Saya senang membongkar dan merakit mesin atau alat mekanik', 'kategori' => 'bakat', 'rules' => ['Teknik Mesin' => 0.88, 'Teknik Perkapalan' => 0.60, 'Teknik Industri' => 0.40]],
    ['teks' => 'Saya tertarik pada dunia perkapalan dan transportasi laut', 'kategori' => 'minat', 'rules' => ['Teknik Perkapalan' => 0.90, 'Perikanan' => 0.35, 'Teknik Mesin' => 0.35]],
    ['teks' => 'Saya menyukai pelajaran Kimia', 'kategori' => 'minat', 'rules' => ['Kimia' => 0.88, 'Teknik Kimia' => 0.85, 'Farmasi' => 0.60, 'Teknik Lingkungan' => 0.55, 'Gizi' => 0.45]],
    ['teks' => 'Saya senang melakukan eksperimen di laboratorium', 'kategori' => 'kemampuan', 'rules' => ['Kimia' => 0.80, 'Biologi' => 0.78, 'Fisika' => 0.72, 'Teknik Kimia' => 0.70, 'Farmasi' => 0.60]],
    ['teks' => 'Saya peduli pada isu lingkungan hidup dan keberlanjutan', 'kategori' => 'minat', 'rules' => ['Teknik Lingkungan' => 0.88, 'Kehutanan' => 0.65, 'Biologi' => 0.45, 'Geografi' => 0.45]],
    ['teks' => 'Saya tertarik pada bangunan, jembatan, dan infrastruktur', 'kategori' => 'minat', 'rules' => ['Teknik Sipil' => 0.88, 'Arsitektur' => 0.55, 'Perencanaan Wilayah dan Kota' => 0.50]],
    ['teks' => 'Saya senang menggambar dan mendesain ruang atau bangunan', 'kategori' => 'bakat', 'rules' => ['Arsitektur' => 0.90, 'Desain Komunikasi Visual' => 0.40, 'Teknik Sipil' => 0.45, 'Desain Produk' => 0.50]],
    ['teks' => 'Saya senang mengatur efisiensi proses kerja dan produksi', 'kategori' => 'minat', 'rules' => ['Teknik Industri' => 0.88, 'Manajemen' => 0.50, 'Agribisnis' => 0.35]],
    ['teks' => 'Saya menyukai pelajaran Biologi dan tertarik pada makhluk hidup/ekosistem', 'kategori' => 'minat', 'rules' => ['Biologi' => 0.88, 'Kehutanan' => 0.55, 'Perikanan' => 0.50, 'Kedokteran Hewan' => 0.45]],
    ['teks' => 'Saya tertarik pada pertanian, tanaman, dan cara budidayanya', 'kategori' => 'minat', 'rules' => ['Agroteknologi' => 0.88, 'Agribisnis' => 0.55, 'Ilmu dan Teknologi Pangan' => 0.45]],
    ['teks' => 'Saya senang bekerja di lapangan atau kebun secara langsung', 'kategori' => 'kepribadian', 'rules' => ['Agroteknologi' => 0.75, 'Kehutanan' => 0.65, 'Peternakan' => 0.60, 'Perikanan' => 0.55]],
    ['teks' => 'Saya menyukai dan peduli pada hewan ternak/peliharaan', 'kategori' => 'minat', 'rules' => ['Peternakan' => 0.88, 'Kedokteran Hewan' => 0.55]],
    ['teks' => 'Saya tertarik pada dunia kelautan dan budidaya perikanan', 'kategori' => 'minat', 'rules' => ['Perikanan' => 0.88, 'Teknik Perkapalan' => 0.30]],
    ['teks' => 'Saya peduli pada kelestarian hutan dan alam liar', 'kategori' => 'minat', 'rules' => ['Kehutanan' => 0.88, 'Teknik Lingkungan' => 0.50, 'Biologi' => 0.40]],
    ['teks' => 'Saya tertarik pada peta, wilayah, dan fenomena kebumian', 'kategori' => 'minat', 'rules' => ['Geografi' => 0.88, 'Perencanaan Wilayah dan Kota' => 0.55]],
    ['teks' => 'Saya senang merancang konsep tata ruang dan pembangunan kota', 'kategori' => 'minat', 'rules' => ['Perencanaan Wilayah dan Kota' => 0.88, 'Arsitektur' => 0.45, 'Geografi' => 0.40]],
    ['teks' => 'Saya menyukai olahraga dan aktivitas fisik', 'kategori' => 'minat', 'rules' => ['Ilmu Keolahragaan' => 0.85, 'Pendidikan Olahraga' => 0.85]],
    ['teks' => 'Saya memiliki stamina dan koordinasi tubuh yang baik', 'kategori' => 'bakat', 'rules' => ['Ilmu Keolahragaan' => 0.80, 'Pendidikan Olahraga' => 0.78]],
    ['teks' => 'Saya senang melatih dan membimbing orang lain berolahraga', 'kategori' => 'tujuan_karier', 'rules' => ['Pendidikan Olahraga' => 0.85, 'Ilmu Keolahragaan' => 0.65]],
    ['teks' => 'Saya senang menghitung dan bekerja dengan angka secara presisi', 'kategori' => 'bakat', 'rules' => ['Akuntansi' => 0.85, 'Statistika' => 0.75, 'Matematika' => 0.70, 'Aktuaria' => 0.85, 'Ekonomi Pembangunan' => 0.55]],
    ['teks' => 'Saya tertarik pada risiko keuangan dan perhitungan asuransi', 'kategori' => 'minat', 'rules' => ['Aktuaria' => 0.90, 'Perbankan dan Keuangan' => 0.55, 'Statistika' => 0.45]],
    ['teks' => 'Saya senang bereksperimen dengan alat elektronik sederhana', 'kategori' => 'bakat', 'rules' => ['Teknik Elektro' => 0.80, 'Teknik Komputer' => 0.65, 'Fisika' => 0.45]],
    ['teks' => 'Saya tertarik pada teknologi pengolahan pangan modern', 'kategori' => 'minat', 'rules' => ['Ilmu dan Teknologi Pangan' => 0.90, 'Gizi' => 0.45, 'Agroteknologi' => 0.35]],
    ['teks' => 'Saya senang meneliti reaksi dan struktur zat kimia', 'kategori' => 'minat', 'rules' => ['Kimia' => 0.85, 'Teknik Kimia' => 0.75, 'Farmasi' => 0.50]],
    ['teks' => 'Saya tertarik pada fenomena alam semesta dan energi', 'kategori' => 'minat', 'rules' => ['Fisika' => 0.88, 'Teknik Elektro' => 0.45, 'Geografi' => 0.35]],
    ['teks' => 'Saya senang menganalisis pola dari sekumpulan data statistik', 'kategori' => 'kemampuan', 'rules' => ['Statistika' => 0.88, 'Data Science' => 0.75, 'Aktuaria' => 0.70, 'Ekonomi Pembangunan' => 0.45]],
    ['teks' => 'Saya tertarik pada teknologi internet, jaringan, dan server', 'kategori' => 'minat', 'rules' => ['Teknik Komputer' => 0.85, 'Keamanan Siber' => 0.60, 'Teknik Informatika' => 0.45]],
    ['teks' => 'Saya senang mempelajari kecerdasan buatan (AI) dan machine learning', 'kategori' => 'minat', 'rules' => ['Ilmu Komputer' => 0.88, 'Data Science' => 0.80, 'Teknik Informatika' => 0.55]],
    ['teks' => 'Saya teliti dalam menghitung takaran dan dosis secara akurat', 'kategori' => 'kemampuan', 'rules' => ['Farmasi' => 0.85, 'Gizi' => 0.60, 'Kedokteran' => 0.50]],
    ['teks' => 'Saya sabar menghadapi pasien atau klien dalam waktu lama', 'kategori' => 'kepribadian', 'rules' => ['Kedokteran Gigi' => 0.80, 'Keperawatan' => 0.78, 'Psikologi' => 0.60, 'Bimbingan dan Konseling' => 0.65]],
    ['teks' => 'Saya tertarik pada industri kimia, energi, atau petrokimia', 'kategori' => 'tujuan_karier', 'rules' => ['Teknik Kimia' => 0.85, 'Kimia' => 0.40]],
    ['teks' => 'Saya ingin berkontribusi pada ketahanan pangan nasional', 'kategori' => 'tujuan_karier', 'rules' => ['Agroteknologi' => 0.75, 'Agribisnis' => 0.60, 'Ilmu dan Teknologi Pangan' => 0.65, 'Peternakan' => 0.45, 'Perikanan' => 0.45]],
    ['teks' => 'Saya bercita-cita bekerja di industri teknologi atau startup digital', 'kategori' => 'tujuan_karier', 'rules' => ['Teknik Informatika' => 0.75, 'Ilmu Komputer' => 0.72, 'Sistem Informasi' => 0.65, 'Bisnis Digital' => 0.65, 'Data Science' => 0.60]],
    ['teks' => 'Saya ingin menjadi peneliti atau ilmuwan di masa depan', 'kategori' => 'tujuan_karier', 'rules' => ['Fisika' => 0.70, 'Kimia' => 0.68, 'Biologi' => 0.68, 'Matematika' => 0.60, 'Ilmu Komputer' => 0.50]],

    // ================= LAYER 2 (Q51-100): BISNIS, SOSIAL, HUKUM, PENDIDIKAN =================
    ['teks' => 'Saya senang mengatur dan memimpin sebuah tim', 'kategori' => 'bakat', 'rules' => ['Manajemen' => 0.85, 'Ilmu Administrasi Negara' => 0.45, 'Teknik Industri' => 0.45, 'Ilmu Pemerintahan' => 0.40]],
    ['teks' => 'Saya tertarik pada strategi bisnis dan pengambilan keputusan', 'kategori' => 'minat', 'rules' => ['Manajemen' => 0.88, 'Bisnis Digital' => 0.55, 'Ekonomi Pembangunan' => 0.45]],
    ['teks' => 'Saya menyukai angka dan senang menyusun laporan keuangan', 'kategori' => 'minat', 'rules' => ['Akuntansi' => 0.90, 'Perbankan dan Keuangan' => 0.55, 'Manajemen' => 0.40]],
    ['teks' => 'Saya tertarik pada isu ekonomi makro dan kebijakan pemerintah', 'kategori' => 'minat', 'rules' => ['Ekonomi Pembangunan' => 0.88, 'Ilmu Pemerintahan' => 0.40, 'Ilmu Administrasi Negara' => 0.35]],
    ['teks' => 'Saya tertarik pada bisnis berbasis teknologi dan media sosial', 'kategori' => 'minat', 'rules' => ['Bisnis Digital' => 0.88, 'Manajemen' => 0.45, 'Ilmu Komunikasi' => 0.40]],
    ['teks' => 'Saya tertarik pada dunia perbankan dan investasi', 'kategori' => 'minat', 'rules' => ['Perbankan dan Keuangan' => 0.88, 'Akuntansi' => 0.45, 'Ekonomi Pembangunan' => 0.45, 'Aktuaria' => 0.35]],
    ['teks' => 'Saya tertarik pada isu keadilan, hukum, dan peraturan', 'kategori' => 'minat', 'rules' => ['Ilmu Hukum' => 0.90]],
    ['teks' => 'Saya senang membaca dan menganalisis kasus atau argumen', 'kategori' => 'kemampuan', 'rules' => ['Ilmu Hukum' => 0.80, 'Ilmu Pemerintahan' => 0.45, 'Sosiologi' => 0.40, 'Jurnalistik' => 0.40]],
    ['teks' => 'Saya memiliki kemampuan berargumentasi dan bernegosiasi', 'kategori' => 'bakat', 'rules' => ['Ilmu Hukum' => 0.78, 'Hubungan Internasional' => 0.55, 'Manajemen' => 0.40]],
    ['teks' => 'Saya senang mengajar dan membimbing anak-anak belajar', 'kategori' => 'minat', 'rules' => ['Pendidikan Guru Sekolah Dasar' => 0.88, 'Pendidikan Matematika' => 0.60, 'Pendidikan Bahasa Inggris' => 0.60, 'Bimbingan dan Konseling' => 0.55]],
    ['teks' => 'Saya memiliki kesabaran tinggi dalam mendampingi orang belajar', 'kategori' => 'kepribadian', 'rules' => ['Pendidikan Guru Sekolah Dasar' => 0.80, 'Pendidikan Matematika' => 0.72, 'Bimbingan dan Konseling' => 0.75]],
    ['teks' => 'Saya senang menjelaskan konsep matematika dengan cara sederhana', 'kategori' => 'bakat', 'rules' => ['Pendidikan Matematika' => 0.88, 'Matematika' => 0.45]],
    ['teks' => 'Saya menyukai pelajaran dan berkomunikasi dalam Bahasa Inggris', 'kategori' => 'minat', 'rules' => ['Pendidikan Bahasa Inggris' => 0.88, 'Sastra Inggris' => 0.80, 'Hubungan Internasional' => 0.45]],
    ['teks' => 'Saya senang mendengarkan masalah dan memberi solusi bagi orang lain', 'kategori' => 'minat', 'rules' => ['Bimbingan dan Konseling' => 0.88, 'Psikologi' => 0.80, 'Sosiologi' => 0.35]],
    ['teks' => 'Saya tertarik memahami perilaku dan pikiran manusia', 'kategori' => 'minat', 'rules' => ['Psikologi' => 0.90, 'Bimbingan dan Konseling' => 0.55, 'Sosiologi' => 0.45]],
    ['teks' => 'Saya memiliki empati dan kepekaan sosial yang tinggi', 'kategori' => 'kepribadian', 'rules' => ['Psikologi' => 0.80, 'Bimbingan dan Konseling' => 0.78, 'Sosiologi' => 0.55, 'Keperawatan' => 0.50]],
    ['teks' => 'Saya tertarik pada isu politik, pemerintahan, dan kebijakan publik', 'kategori' => 'minat', 'rules' => ['Ilmu Pemerintahan' => 0.88, 'Ilmu Politik' => 0.85, 'Ilmu Administrasi Negara' => 0.60, 'Hubungan Internasional' => 0.45]],
    ['teks' => 'Saya senang mengikuti dan menganalisis berita politik nasional', 'kategori' => 'minat', 'rules' => ['Ilmu Politik' => 0.85, 'Ilmu Pemerintahan' => 0.65, 'Jurnalistik' => 0.45]],
    ['teks' => 'Saya tertarik pada fenomena sosial dan interaksi masyarakat', 'kategori' => 'minat', 'rules' => ['Sosiologi' => 0.88, 'Ilmu Administrasi Negara' => 0.35, 'Psikologi' => 0.35]],
    ['teks' => 'Saya tertarik pada isu global, diplomasi, dan budaya negara lain', 'kategori' => 'minat', 'rules' => ['Hubungan Internasional' => 0.88, 'Sastra Inggris' => 0.40]],
    ['teks' => 'Saya tertarik pada tata kelola dan pelayanan pemerintahan', 'kategori' => 'minat', 'rules' => ['Ilmu Administrasi Negara' => 0.88, 'Ilmu Pemerintahan' => 0.55]],
    ['teks' => 'Saya senang berbicara di depan umum dan menyampaikan pesan', 'kategori' => 'bakat', 'rules' => ['Ilmu Komunikasi' => 0.85, 'Jurnalistik' => 0.60, 'Hubungan Internasional' => 0.40, 'Pendidikan Guru Sekolah Dasar' => 0.35]],
    ['teks' => 'Saya senang menulis berita, artikel, atau opini', 'kategori' => 'bakat', 'rules' => ['Jurnalistik' => 0.88, 'Ilmu Komunikasi' => 0.55, 'Sastra Indonesia' => 0.50]],
    ['teks' => 'Saya kritis dalam menganalisis suatu peristiwa atau isu', 'kategori' => 'kemampuan', 'rules' => ['Jurnalistik' => 0.80, 'Ilmu Politik' => 0.55, 'Sosiologi' => 0.50, 'Ilmu Hukum' => 0.45]],
    ['teks' => 'Saya senang membaca dan mengoleksi karya sastra atau buku', 'kategori' => 'minat', 'rules' => ['Sastra Indonesia' => 0.85, 'Ilmu Perpustakaan' => 0.70, 'Sastra Inggris' => 0.55]],
    ['teks' => 'Saya senang menulis puisi, cerita, atau karya kreatif lainnya', 'kategori' => 'bakat', 'rules' => ['Sastra Indonesia' => 0.85, 'Jurnalistik' => 0.45, 'Desain Komunikasi Visual' => 0.30]],
    ['teks' => 'Saya teliti dalam mengklasifikasikan dan mengelola informasi', 'kategori' => 'kemampuan', 'rules' => ['Ilmu Perpustakaan' => 0.85, 'Sistem Informasi' => 0.40, 'Ilmu Administrasi Negara' => 0.40]],
    ['teks' => 'Saya senang menggambar, melukis, atau berkarya visual', 'kategori' => 'bakat', 'rules' => ['Desain Komunikasi Visual' => 0.88, 'Arsitektur' => 0.45, 'Desain Produk' => 0.65, 'Seni Musik' => 0.25]],
    ['teks' => 'Saya memiliki jiwa seni dan kepekaan estetika yang tinggi', 'kategori' => 'kepribadian', 'rules' => ['Desain Komunikasi Visual' => 0.80, 'Arsitektur' => 0.55, 'Seni Musik' => 0.65, 'Desain Produk' => 0.68]],
    ['teks' => 'Saya menyukai musik dan senang bermain alat musik', 'kategori' => 'minat', 'rules' => ['Seni Musik' => 0.90]],
    ['teks' => 'Saya senang merancang produk fisik yang fungsional dan estetis', 'kategori' => 'minat', 'rules' => ['Desain Produk' => 0.88, 'Desain Komunikasi Visual' => 0.40, 'Teknik Industri' => 0.35, 'Arsitektur' => 0.35]],
    ['teks' => 'Saya ingin bekerja di bidang keuangan atau perbankan', 'kategori' => 'tujuan_karier', 'rules' => ['Akuntansi' => 0.70, 'Perbankan dan Keuangan' => 0.80, 'Aktuaria' => 0.55, 'Manajemen' => 0.40]],
    ['teks' => 'Saya bercita-cita menjadi pengacara, hakim, atau notaris', 'kategori' => 'tujuan_karier', 'rules' => ['Ilmu Hukum' => 0.90]],
    ['teks' => 'Saya bercita-cita menjadi guru atau pendidik profesional', 'kategori' => 'tujuan_karier', 'rules' => ['Pendidikan Guru Sekolah Dasar' => 0.85, 'Pendidikan Matematika' => 0.82, 'Pendidikan Bahasa Inggris' => 0.82, 'Bimbingan dan Konseling' => 0.60]],
    ['teks' => 'Saya ingin berkarier di bidang pemerintahan atau menjadi ASN', 'kategori' => 'tujuan_karier', 'rules' => ['Ilmu Pemerintahan' => 0.85, 'Ilmu Administrasi Negara' => 0.85, 'Ilmu Hukum' => 0.40, 'Ilmu Politik' => 0.50]],
    ['teks' => 'Saya ingin berkarier di dunia media, pers, atau jurnalistik', 'kategori' => 'tujuan_karier', 'rules' => ['Jurnalistik' => 0.88, 'Ilmu Komunikasi' => 0.65]],
    ['teks' => 'Saya ingin menjadi psikolog atau konselor profesional', 'kategori' => 'tujuan_karier', 'rules' => ['Psikologi' => 0.88, 'Bimbingan dan Konseling' => 0.82]],
    ['teks' => 'Saya ingin menjadi diplomat atau bekerja di organisasi internasional', 'kategori' => 'tujuan_karier', 'rules' => ['Hubungan Internasional' => 0.88, 'Ilmu Politik' => 0.40]],
    ['teks' => 'Saya ingin membangun bisnis atau menjadi wirausahawan', 'kategori' => 'tujuan_karier', 'rules' => ['Manajemen' => 0.75, 'Bisnis Digital' => 0.78, 'Agribisnis' => 0.55]],
    ['teks' => 'Saya senang bernegosiasi dan meyakinkan orang lain', 'kategori' => 'bakat', 'rules' => ['Manajemen' => 0.65, 'Ilmu Hukum' => 0.55, 'Hubungan Internasional' => 0.50, 'Bisnis Digital' => 0.45]],
    ['teks' => 'Saya teliti dalam mengikuti prosedur dan aturan administratif', 'kategori' => 'kemampuan', 'rules' => ['Ilmu Administrasi Negara' => 0.80, 'Akuntansi' => 0.55, 'Ilmu Hukum' => 0.45]],
    ['teks' => 'Saya senang mempelajari budaya dan bahasa asing', 'kategori' => 'minat', 'rules' => ['Sastra Inggris' => 0.85, 'Hubungan Internasional' => 0.70, 'Pendidikan Bahasa Inggris' => 0.55]],
    ['teks' => 'Saya senang menganalisis rantai pasok dan proses bisnis pertanian', 'kategori' => 'minat', 'rules' => ['Agribisnis' => 0.85, 'Manajemen' => 0.35, 'Teknik Industri' => 0.35]],
    ['teks' => 'Saya tertarik pada psikologi kerja dan pengembangan SDM', 'kategori' => 'minat', 'rules' => ['Psikologi' => 0.65, 'Manajemen' => 0.55, 'Ilmu Administrasi Negara' => 0.35]],
    ['teks' => 'Saya senang mengelola dan menganalisis anggaran/keuangan organisasi', 'kategori' => 'kemampuan', 'rules' => ['Akuntansi' => 0.80, 'Manajemen' => 0.55, 'Ekonomi Pembangunan' => 0.50, 'Ilmu Administrasi Negara' => 0.40]],
    ['teks' => 'Saya senang membuat konten kreatif untuk media sosial', 'kategori' => 'bakat', 'rules' => ['Bisnis Digital' => 0.75, 'Ilmu Komunikasi' => 0.65, 'Desain Komunikasi Visual' => 0.55, 'Jurnalistik' => 0.40]],
    ['teks' => 'Saya tertarik mempelajari sejarah dan perkembangan peradaban', 'kategori' => 'minat', 'rules' => ['Sosiologi' => 0.55, 'Sastra Indonesia' => 0.45, 'Ilmu Pemerintahan' => 0.35, 'Hubungan Internasional' => 0.35]],
    ['teks' => 'Saya senang bekerja dengan target dan tenggat waktu yang jelas', 'kategori' => 'kepribadian', 'rules' => ['Manajemen' => 0.55, 'Akuntansi' => 0.55, 'Teknik Industri' => 0.55, 'Jurnalistik' => 0.45]],
    ['teks' => 'Saya senang membaca laporan dan menyusun rekomendasi kebijakan', 'kategori' => 'kemampuan', 'rules' => ['Ekonomi Pembangunan' => 0.65, 'Ilmu Pemerintahan' => 0.60, 'Ilmu Administrasi Negara' => 0.60, 'Ilmu Politik' => 0.55]],
    ['teks' => 'Saya nyaman bekerja di lingkungan yang tenang dan terstruktur', 'kategori' => 'kepribadian', 'rules' => ['Ilmu Perpustakaan' => 0.65, 'Akuntansi' => 0.50, 'Statistika' => 0.45]],

    // ================= LAYER 3 (Q101-150): KEPRIBADIAN UMUM & LINTAS BIDANG =================
    ['teks' => 'Saya lebih suka bekerja dalam tim daripada sendirian', 'kategori' => 'kepribadian', 'rules' => ['Manajemen' => 0.55, 'Teknik Industri' => 0.55, 'Ilmu Komunikasi' => 0.50, 'Pendidikan Guru Sekolah Dasar' => 0.45]],
    ['teks' => 'Saya lebih suka bekerja secara mandiri dan fokus sendiri', 'kategori' => 'kepribadian', 'rules' => ['Ilmu Komputer' => 0.50, 'Statistika' => 0.50, 'Sastra Indonesia' => 0.45, 'Akuntansi' => 0.45]],
    ['teks' => 'Saya senang menghadapi tantangan dan masalah baru', 'kategori' => 'kepribadian', 'rules' => ['Teknik Informatika' => 0.55, 'Ilmu Hukum' => 0.45, 'Manajemen' => 0.45, 'Keamanan Siber' => 0.55]],
    ['teks' => 'Saya cenderung berpikir sistematis dan runtut', 'kategori' => 'kepribadian', 'rules' => ['Teknik Informatika' => 0.55, 'Matematika' => 0.60, 'Teknik Industri' => 0.55, 'Akuntansi' => 0.50]],
    ['teks' => 'Saya cenderung kreatif dan menyukai hal-hal baru', 'kategori' => 'kepribadian', 'rules' => ['Desain Komunikasi Visual' => 0.60, 'Bisnis Digital' => 0.50, 'Seni Musik' => 0.55, 'Arsitektur' => 0.50, 'Desain Produk' => 0.55]],
    ['teks' => 'Saya senang memimpin diskusi atau menjadi ketua kelompok', 'kategori' => 'kepribadian', 'rules' => ['Manajemen' => 0.55, 'Ilmu Pemerintahan' => 0.50, 'Ilmu Politik' => 0.50, 'Hubungan Internasional' => 0.40]],
    ['teks' => 'Saya lebih suka mengikuti arahan daripada memimpin', 'kategori' => 'kepribadian', 'rules' => ['Akuntansi' => 0.40, 'Keperawatan' => 0.40, 'Ilmu Perpustakaan' => 0.40]],
    ['teks' => 'Saya senang membantu menyelesaikan masalah orang lain', 'kategori' => 'kepribadian', 'rules' => ['Psikologi' => 0.55, 'Bimbingan dan Konseling' => 0.60, 'Ilmu Hukum' => 0.40, 'Keperawatan' => 0.45]],
    ['teks' => 'Saya senang berkompetisi dan mengejar prestasi terbaik', 'kategori' => 'kepribadian', 'rules' => ['Manajemen' => 0.45, 'Ilmu Keolahragaan' => 0.55, 'Bisnis Digital' => 0.45, 'Aktuaria' => 0.35]],
    ['teks' => 'Saya cukup perfeksionis dan sangat detail dalam bekerja', 'kategori' => 'kepribadian', 'rules' => ['Akuntansi' => 0.55, 'Arsitektur' => 0.50, 'Farmasi' => 0.50, 'Kedokteran Gigi' => 0.55]],
    ['teks' => 'Saya fleksibel dan mudah beradaptasi dengan perubahan', 'kategori' => 'kepribadian', 'rules' => ['Bisnis Digital' => 0.50, 'Ilmu Komunikasi' => 0.45, 'Hubungan Internasional' => 0.45]],
    ['teks' => 'Saya senang berbicara dan berinteraksi dengan orang baru', 'kategori' => 'kepribadian', 'rules' => ['Ilmu Komunikasi' => 0.55, 'Manajemen' => 0.45, 'Hubungan Internasional' => 0.50, 'Jurnalistik' => 0.45]],
    ['teks' => 'Saya lebih nyaman bekerja di balik layar tanpa banyak tampil', 'kategori' => 'kepribadian', 'rules' => ['Teknik Informatika' => 0.45, 'Akuntansi' => 0.45, 'Ilmu Perpustakaan' => 0.50, 'Data Science' => 0.45]],
    ['teks' => 'Saya senang merencanakan sesuatu secara matang sebelum bertindak', 'kategori' => 'kepribadian', 'rules' => ['Manajemen' => 0.50, 'Perencanaan Wilayah dan Kota' => 0.60, 'Teknik Industri' => 0.50, 'Ekonomi Pembangunan' => 0.45]],
    ['teks' => 'Saya senang mengambil keputusan cepat dalam tekanan', 'kategori' => 'kepribadian', 'rules' => ['Kedokteran' => 0.55, 'Keperawatan' => 0.55, 'Manajemen' => 0.45, 'Jurnalistik' => 0.40]],
    ['teks' => 'Saya menyukai pekerjaan yang melibatkan aktivitas fisik atau lapangan', 'kategori' => 'kepribadian', 'rules' => ['Teknik Sipil' => 0.50, 'Kehutanan' => 0.55, 'Agroteknologi' => 0.50, 'Ilmu Keolahragaan' => 0.55, 'Teknik Perkapalan' => 0.45]],
    ['teks' => 'Saya lebih menyukai pekerjaan di dalam ruangan yang tenang', 'kategori' => 'kepribadian', 'rules' => ['Akuntansi' => 0.45, 'Ilmu Komputer' => 0.40, 'Sastra Indonesia' => 0.40, 'Statistika' => 0.40]],
    ['teks' => 'Saya senang belajar hal baru secara mandiri lewat internet', 'kategori' => 'kepribadian', 'rules' => ['Teknik Informatika' => 0.50, 'Bisnis Digital' => 0.45, 'Data Science' => 0.50, 'Desain Komunikasi Visual' => 0.40]],
    ['teks' => 'Saya senang menjaga penampilan dan estetika visual sesuatu', 'kategori' => 'kepribadian', 'rules' => ['Desain Komunikasi Visual' => 0.55, 'Arsitektur' => 0.50, 'Desain Produk' => 0.55]],
    ['teks' => 'Saya senang menganalisis untung-rugi sebelum mengambil keputusan', 'kategori' => 'kepribadian', 'rules' => ['Akuntansi' => 0.55, 'Manajemen' => 0.50, 'Ekonomi Pembangunan' => 0.55, 'Perbankan dan Keuangan' => 0.55]],
    ['teks' => 'Saya bersemangat menjadi sukarelawan atau kegiatan sosial', 'kategori' => 'kepribadian', 'rules' => ['Sosiologi' => 0.55, 'Bimbingan dan Konseling' => 0.45, 'Keperawatan' => 0.40, 'Ilmu Administrasi Negara' => 0.35]],
    ['teks' => 'Saya menyukai kegiatan yang melibatkan hitungan probabilitas dan risiko', 'kategori' => 'bakat', 'rules' => ['Aktuaria' => 0.85, 'Statistika' => 0.70, 'Perbankan dan Keuangan' => 0.45]],
    ['teks' => 'Saya mampu menjelaskan hal rumit dengan bahasa yang mudah dipahami', 'kategori' => 'bakat', 'rules' => ['Pendidikan Matematika' => 0.65, 'Jurnalistik' => 0.55, 'Ilmu Komunikasi' => 0.50, 'Bimbingan dan Konseling' => 0.45]],
    ['teks' => 'Saya cepat memahami pola dan hubungan antar data', 'kategori' => 'bakat', 'rules' => ['Data Science' => 0.75, 'Statistika' => 0.72, 'Matematika' => 0.65, 'Aktuaria' => 0.65]],
    ['teks' => 'Saya senang merancang sistem atau proses yang efisien', 'kategori' => 'bakat', 'rules' => ['Teknik Industri' => 0.75, 'Sistem Informasi' => 0.55, 'Manajemen' => 0.45]],
    ['teks' => 'Saya memiliki kepekaan terhadap nada, irama, dan bunyi', 'kategori' => 'bakat', 'rules' => ['Seni Musik' => 0.88]],
    ['teks' => 'Saya cekatan menggunakan tangan untuk pekerjaan yang presisi', 'kategori' => 'bakat', 'rules' => ['Kedokteran Gigi' => 0.70, 'Farmasi' => 0.55, 'Desain Produk' => 0.55, 'Teknik Mesin' => 0.50]],
    ['teks' => 'Saya mudah mengingat detail kecil dan informasi spesifik', 'kategori' => 'bakat', 'rules' => ['Ilmu Perpustakaan' => 0.65, 'Ilmu Hukum' => 0.55, 'Akuntansi' => 0.55, 'Kedokteran' => 0.50]],
    ['teks' => 'Saya mampu bekerja di bawah tekanan dengan tenang', 'kategori' => 'kemampuan', 'rules' => ['Kedokteran' => 0.65, 'Keperawatan' => 0.68, 'Jurnalistik' => 0.55, 'Manajemen' => 0.50]],
    ['teks' => 'Saya mampu menyampaikan ide secara persuasif dan meyakinkan', 'kategori' => 'kemampuan', 'rules' => ['Ilmu Hukum' => 0.60, 'Manajemen' => 0.55, 'Bisnis Digital' => 0.50, 'Hubungan Internasional' => 0.50]],
    ['teks' => 'Saya mampu bekerja dengan software desain atau editing', 'kategori' => 'kemampuan', 'rules' => ['Desain Komunikasi Visual' => 0.80, 'Arsitektur' => 0.45, 'Desain Produk' => 0.60, 'Jurnalistik' => 0.35]],
    ['teks' => 'Saya mampu menyusun tulisan yang runtut dan mudah dipahami', 'kategori' => 'kemampuan', 'rules' => ['Sastra Indonesia' => 0.70, 'Jurnalistik' => 0.75, 'Ilmu Hukum' => 0.45, 'Ilmu Komunikasi' => 0.50]],
    ['teks' => 'Saya mampu berpikir kritis dan mengevaluasi berbagai sudut pandang', 'kategori' => 'kemampuan', 'rules' => ['Ilmu Hukum' => 0.65, 'Ilmu Politik' => 0.60, 'Sosiologi' => 0.55, 'Ilmu Pemerintahan' => 0.50]],
    ['teks' => 'Saya mampu mengoperasikan berbagai peralatan teknis dengan cepat', 'kategori' => 'kemampuan', 'rules' => ['Teknik Elektro' => 0.60, 'Teknik Mesin' => 0.60, 'Teknik Komputer' => 0.55]],
    ['teks' => 'Saya ingin menjadi pengusaha di bidang pertanian atau pangan', 'kategori' => 'tujuan_karier', 'rules' => ['Agribisnis' => 0.80, 'Ilmu dan Teknologi Pangan' => 0.55, 'Agroteknologi' => 0.45]],
    ['teks' => 'Saya ingin berkarier di industri kreatif dan hiburan', 'kategori' => 'tujuan_karier', 'rules' => ['Desain Komunikasi Visual' => 0.70, 'Seni Musik' => 0.75, 'Jurnalistik' => 0.45, 'Ilmu Komunikasi' => 0.45]],
    ['teks' => 'Saya ingin bekerja di perusahaan multinasional atau luar negeri', 'kategori' => 'tujuan_karier', 'rules' => ['Hubungan Internasional' => 0.65, 'Manajemen' => 0.50, 'Sastra Inggris' => 0.50, 'Bisnis Digital' => 0.45]],
    ['teks' => 'Saya ingin menjadi peneliti kebijakan atau bekerja di lembaga think-tank', 'kategori' => 'tujuan_karier', 'rules' => ['Ekonomi Pembangunan' => 0.65, 'Ilmu Politik' => 0.60, 'Sosiologi' => 0.55, 'Ilmu Pemerintahan' => 0.55]],
    ['teks' => 'Saya ingin bekerja di sektor energi, tambang, atau migas', 'kategori' => 'tujuan_karier', 'rules' => ['Teknik Kimia' => 0.65, 'Teknik Elektro' => 0.45, 'Geografi' => 0.45, 'Teknik Mesin' => 0.45]],
    ['teks' => 'Saya ingin berkontribusi menjaga kelestarian laut dan pesisir', 'kategori' => 'tujuan_karier', 'rules' => ['Perikanan' => 0.80, 'Teknik Lingkungan' => 0.45, 'Teknik Perkapalan' => 0.35]],
    ['teks' => 'Saya ingin bekerja sebagai analis data atau data scientist', 'kategori' => 'tujuan_karier', 'rules' => ['Data Science' => 0.90, 'Statistika' => 0.70, 'Sistem Informasi' => 0.45]],
    ['teks' => 'Saya ingin berkarier sebagai arsitek atau desainer profesional', 'kategori' => 'tujuan_karier', 'rules' => ['Arsitektur' => 0.90, 'Desain Produk' => 0.55, 'Desain Komunikasi Visual' => 0.45]],
    ['teks' => 'Saya ingin bekerja di bidang riset dan pengembangan (R&D)', 'kategori' => 'tujuan_karier', 'rules' => ['Kimia' => 0.55, 'Fisika' => 0.55, 'Biologi' => 0.55, 'Teknik Kimia' => 0.50, 'Ilmu dan Teknologi Pangan' => 0.50]],
    ['teks' => 'Saya ingin menjadi ahli statistik atau aktuaris bersertifikat', 'kategori' => 'tujuan_karier', 'rules' => ['Statistika' => 0.85, 'Aktuaria' => 0.90]],
    ['teks' => 'Saya ingin bekerja sebagai konsultan manajemen atau bisnis', 'kategori' => 'tujuan_karier', 'rules' => ['Manajemen' => 0.75, 'Teknik Industri' => 0.55, 'Ekonomi Pembangunan' => 0.45]],
    ['teks' => 'Saya ingin mengajar di perguruan tinggi atau menjadi dosen', 'kategori' => 'tujuan_karier', 'rules' => ['Pendidikan Matematika' => 0.60, 'Pendidikan Bahasa Inggris' => 0.55, 'Fisika' => 0.40, 'Sastra Indonesia' => 0.40]],
    ['teks' => 'Saya ingin bekerja sebagai perencana kota atau ahli tata ruang', 'kategori' => 'tujuan_karier', 'rules' => ['Perencanaan Wilayah dan Kota' => 0.90, 'Geografi' => 0.45, 'Arsitektur' => 0.40]],
    ['teks' => 'Saya ingin bekerja di bidang keamanan siber atau digital forensik', 'kategori' => 'tujuan_karier', 'rules' => ['Keamanan Siber' => 0.90, 'Teknik Informatika' => 0.35]],
    ['teks' => 'Saya ingin bekerja sebagai apoteker atau di industri farmasi', 'kategori' => 'tujuan_karier', 'rules' => ['Farmasi' => 0.90]],
    ['teks' => 'Saya ingin bekerja sebagai ahli gizi klinis atau konsultan kesehatan', 'kategori' => 'tujuan_karier', 'rules' => ['Gizi' => 0.90, 'Kedokteran' => 0.30]],
];
